apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kubeflow-training-operator-mutating-webhook-configuration
  labels:
    app.kubernetes.io/name: kubeflow-training-operator
    app.kubernetes.io/part-of: kubeflow-training-operator
webhooks:
- name: mutating.mpijob.kubeflow.org
  clientConfig:
    service:
      name: kubeflow-training-operator
      namespace: openshift-ai
      path: "/mutate/mpijob"
    caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["kubeflow.org"]
    apiVersions: ["v2"]
    resources: ["mpijobs"]
    scope: "Namespaced"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
  failurePolicy: Fail

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kubeflow-training-operator-validating-webhook-configuration
  labels:
    app.kubernetes.io/name: kubeflow-training-operator
    app.kubernetes.io/part-of: kubeflow-training-operator
webhooks:
- name: validating.mpijob.kubeflow.org
  clientConfig:
    service:
      name: kubeflow-training-operator
      namespace: openshift-ai
      path: "/validate/mpijob"
    caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["kubeflow.org"]
    apiVersions: ["v2"]
    resources: ["mpijobs"]
    scope: "Namespaced"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
  failurePolicy: Fail